#!/bin/bash

set -o errexit

echo "Running jekyll doctor"
bundle exec jekyll doctor

echo "Building"
bundle exec jekyll build

echo "Running accessibility checks"

for file in $(find _site -name '*.html' | sed -e 's/_site//') ; do
  echo "Checking $file"
  phantomjs node_modules/accessibility-developer-tools/tools/runner/audit.js http://localhost:4000$file
done
